# Generated by Django 5.1.7 on 2025-03-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delivery Info', 'verbose_name_plural': 'Delivery Info'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment History', 'verbose_name_plural': 'Payment Histories'},
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current delivery status', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], default='cash', help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='predefined_address',
            field=models.CharField(blank=True, choices=[('evelyhone', 'Evelyn Hone College'), ('zambia_police', 'Zambia Police Headquarters'), ('zambia_accountancy', 'Zambia Centre for Accountancy'), ('mukuba_house', 'Mukuba Pension House'), ('bus_terminus', 'Lusaka Intercity Bus Terminus'), ('national_museum', 'Lusaka National Museum')], help_text='Predefined delivery point', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='secondary_phone_number',
            field=models.CharField(blank=True, help_text='Optional secondary contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='delivery_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_histories', to='payments.deliveryinfo'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='items',
            field=models.JSONField(help_text="List of items in the payment (e.g., [{'name': 'Pizza', 'quantity': 2, 'subtotal': 15.00}])"),
        ),
    ]
