# Generated by Django 5.1.7 on 2025-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_deliveryinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='payment_provider',
            field=models.CharField(blank=True, help_text='Specific provider for Mobile Money or Card (e.g., Airtel, Stripe)', max_length=20, null=True),
        ),
    ]
