# Generated by Django 5.1.7 on 2025-03-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_deliveryinfo_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
