# Generated by Django 5.1 on 2025-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymenthistory_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped (Test Mode)'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
