# Generated by Django 5.1 on 2025-05-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymenthistory_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment_status',
        ),
    ]
