# Generated by Django 5.2.1 on 2025-05-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_paymenthistory_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delivery Info', 'verbose_name_plural': 'Delivery Info'},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='is_pos_order',
            field=models.BooleanField(default=False, help_text='Indicates if this is an in-store POS order'),
        ),
    ]
