# Generated by Django 5.2.1 on 2025-05-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment History', 'verbose_name_plural': 'Payment Histories'},
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='is_pos_order',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='is_pos_order',
            field=models.BooleanField(default=False, help_text='Indicates if this is an in-store POS order'),
        ),
    ]
