# Generated by Django 5.2.1 on 2025-06-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_paymenthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='driver_location',
            field=models.JSONField(blank=True, default=dict, help_text='Current driver location coordinates (latitude, longitude)', null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last location update', null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='restaurant_location',
            field=models.JSONField(default=dict, help_text='Fixed restaurant location coordinates'),
        ),
    ]
