# Generated by Django 5.2.1 on 2025-06-07 00:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '__first__'),
        ('payments', '0010_deliveryinfo_driver_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='address',
            field=models.CharField(blank=True, help_text='Custom delivery address, if not using predefined point', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='cart',
            field=models.ForeignKey(help_text='Cart containing order items', on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='driver_location',
            field=models.JSONField(blank=True, help_text='Current driver location coordinates (latitude, longitude)', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='phone_number',
            field=models.CharField(help_text='Primary contact number', max_length=20, validators=[django.core.validators.RegexValidator('^\\+\\d{10,15}$', 'Enter a valid phone number (e.g., +260973546375)')]),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='predefined_address',
            field=models.CharField(blank=True, choices=[('evelynhone', 'Evelyn Hone College'), ('zambia_police', 'Zambia Police Headquarters'), ('zambia_accountancy', 'Zambia Centre for Accountancy'), ('mukuba_house', 'Mukuba Pension House'), ('bus_terminus', 'Lusaka Intercity Bus Terminus'), ('national_museum', 'Lusaka National Museum')], help_text='Predefined delivery point', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='secondary_phone_number',
            field=models.CharField(blank=True, help_text='Optional secondary contact number', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{10,15}$', 'Enter a valid phone number (e.g., +260973546375)')]),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='user',
            field=models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='cart',
            field=models.ForeignKey(help_text='Cart associated with the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='delivery_info',
            field=models.ForeignKey(help_text='Associated delivery information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_histories', to='payments.deliveryinfo'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='items',
            field=models.JSONField(default=list, help_text="List of items in the payment (e.g., [{'name': 'Pizza', 'quantity': 2, 'subtotal': 15.00}])"),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total payment amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from payment provider (e.g., PayPal)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
