# Generated by Django 5.2.1 on 2025-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_deliveryinfo_address_alter_deliveryinfo_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='driver_location',
            field=models.JSONField(blank=True, help_text="Driver coordinates {'lat': float, 'lng': float}", null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='restaurant_location',
            field=models.JSONField(blank=True, help_text="Restaurant coordinates {'lat': float, 'lng': float}", null=True),
        ),
    ]
