# Generated by Django 5.1 on 2025-05-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('ms', 'Ms.'), ('mx', 'Mx.'), ('none', 'Prefer not to say')], max_length=10, null=True),
        ),
    ]
