# Generated by Django 5.1 on 2025-05-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('ms', 'Ms.'), ('', 'Prefer not to say')], max_length=10, null=True),
        ),
    ]
