# Generated by Django 5.2.1 on 2025-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
