# Generated by Django 5.2.1 on 2025-06-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_restaurant_community_r_city_f8136a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Restaurant/'),
        ),
    ]
