# Generated by Django 5.2.1 on 2025-06-25 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_restaurant_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together={('challenge', 'user')},
        ),
    ]
