# Generated by Django 5.2.1 on 2025-06-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_challengeparticipation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeparticipation',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.post'),
        ),
    ]
