# Generated by Django 5.2.1 on 2025-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_challengeparticipation_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='recipe_comments', to='community.comment'),
        ),
    ]
