# Generated by Django 5.1 on 2025-05-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('system', 'System'), ('alert', 'Alert')], default='order_update', max_length=20),
        ),
    ]
