# Generated by Django 5.1 on 2025-05-12 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_notification_notification_type_staffassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[('evelyhone', 'Evelyn Hone College'), ('zambia_police', 'Zambia Police Headquarters'), ('zambia_accountancy', 'Zambia Centre for Accountancy'), ('mukuba_house', 'Mukuba Pension House'), ('bus_terminus', 'Lusaka Intercity Bus Terminus'), ('national_museum', 'Lusaka National Museum')], help_text='Which delivery point this staff covers', max_length=30)),
                ('staff', models.ForeignKey(limit_choices_to={'user_type': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Service Area',
                'verbose_name_plural': 'Staff Service Areas',
                'unique_together': {('staff', 'point')},
            },
        ),
    ]
