# Generated by Django 5.1 on 2025-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_staffservicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('delivery_almost_complete', 'Delivery Almost Complete'), ('delivery_completed', 'Delivery Completed'), ('alert', 'Alert'), ('delivery_declined', 'Delivery Declined')], default='new_order', max_length=30),
        ),
    ]
